### ISSUE TITLE
Worker unable to detect CUDA while working on GPU

### ISSUE THREAD

**Issue by DESHRAJ** [celery/celery#3402]
I am loading a deep learning model to the celery mainprocess but when I try to run a task on the worker, then it shows the following error:

 `$ Error: cuda runtime error (3) : initialization error at /tmp/luarocks_cutorch-scm-1-7999/cutorch/init.c:720`
`THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-7999/cutorch/init.c line=720 error=3 : initialization error`

**Note**: This is a Torch model and when the celery is started then the model is loaded successfully on GPU but when the worker tries to perform the task, then it throws this error. It seems like that the worker is not able to get the CUDA path. 

I tried to add environment variable with the celery process using the following command:

`LD_LIBRARY_PATH="/usr/local/cuda/lib64"  celery --app=demo.celery:celery_app worker --loglevel=DEBUG`
But this is also not working.

Any help will be really appreciated.  :-)

**Comment by ask** [comment]
Maybe related to #2888

Usually with problems like these where it works outside celery, but not in a celery worker, it means that the library. or something you do with the library is not fork-safe.

An example would be if the CUDA library defines some global in C that's shared between parent and child process, causing race conditions.

**Comment by ask** [comment]
One workaround that often work for these problems is to make sure the library is loaded as late as possible (thus it's not imported in the parent process at all).

For example instead of:

```py

import CUDA

@app.task
def t():
   CUDA.something()
```

you can do:

```
app.task
def t():
    import CUDA
    CUDA.something()
```

You would need to take care something else didn't import it as a side effect of the worker importing task modules.

**Comment by DESHRAJ** [comment]
Thanks @ask for answering. The example that you have shared will import CUDA everytime the method `t()` is executed. I am trying to import CUDA in the main process and then use it in the subprocess(worker). But since the problem is that the library is not fork-safe so I have found a workaround that works well with RabbitMQ.

**Comment by geoffoxholm** [comment]
@deshraj - What was your workaround?

**Comment by deshraj** [comment]
@geoffoxholm I could not resolve this problem using Celery since the process needs to be fork safe. So, I finally shifted to RabbitMQ and now it's working flawlessly. Please let me know if you can find a workaround for the same. :-)

**Comment by geoffoxholm** [comment]
I'm new to this stuff, but I think I'm using RabbitMQ to do the job messaging, and Celery to run the workers. In my case I setup 4 workers, and had each one secure its own GPU only at run time.

**Comment by pietrek928** [comment]
For me setting `worker_pool = 'solo'` in celery config helped.
Setting this option disables forking which breaks using pytorch
